# Load path
load_path_root: "/home/RVLuser/data/kitchen_data/bags" # Path to bags

# Save path
save_path_root: "/home/RVLuser/data/kitchen_data/segmented_data"

# Save folders
rgb_folder: "rgb"
rgb_seg_folder: "rgb_seg"
depth_seg_folder: "depth_seg"
ply_seg_folder: "PLY_seg"

# Images and rosbag config
camera_fps: 15
wanted_fps: 5
rgb_topic: "/camera/color/image_raw"
depth_topic: "/camera/aligned_depth_to_color/image_raw"
camera_info_topic: "/camera/color/camera_info"
# rgb_topic: "/camera/rgb/image_rect_color"
# depth_topic: "/camera/depth_registered/image_raw"
# camera_info_topic: "/camera/rgb/camera_info"
bag_reproduce_rate: 0.25

# Detectron2 config
model_path: "/home/RVLuser/data/weights/TensorMask/tensormask_R_50_FPN_1x.pkl"
config_path: "/opt/detectron2/projects/TensorMask/configs/tensormask_R_50_FPN_1x.yaml"
roi_heads_threshold: 0.5
instance_threshold: 0.4
visualize_images: True
save_images: True